### ISSUE TITLE
Impossible to login - page instantly reloads and logs you out

### ISSUE THREAD

**Issue by spacecowboy** [blockchain/My-Wallet-V3-Frontend#1253] opened 2017-08-16 21:12 UTC
# Summary

I am unable to login to my wallet in any functional way because the page instantly reloads and logs me out. I can provide a screen recording of the bug in action but I'm not putting it on a public site.

# Steps to reproduce

1.
Go to https://blockchain.info/wallet/#/login 
and login to your account.

And yes, correct ID / password / 2FA are all given

# Expected result

I am logged in and able to interact with my wallet.

# What actually happens

I am logged in for about 300ms before the entire page reloads and sends me back to https://blockchain.info/ . Trying to go back to https://blockchain.info/wallet/#/home redirects me to the login page. So I am effectively locked out of my wallet.

# Browsers used

Firefox 55 and Chromium 60.0.3112.78

# Version of app

Whatever is hosted on blockchain.info at the moment

**Comment by jtormey** [comment] 2017-08-16 21:16
Hi, are you able to see any errors in the Javascript console before you're redirected to blockchain.info?

**Comment by jtormey** [comment] 2017-08-16 21:19
Also, do you have second password active?

**Comment by spacecowboy** [comment] 2017-08-16 22:00
hey @jtormey thanks for helping out. Support asked me to give you my wallet id: 
`74815698-7edc-5ebf-8d37-aad3b6f9074f`

>are you able to see any errors in the Javascript console before you're redirected to blockchain.info?

I do see this strange message in the console

![screenshot from 2017-08-16 23-55-48](https://user-images.githubusercontent.com/223655/29387008-74d535ea-82de-11e7-8fbb-6ac488840a5e.png)

but these errors seem to be more relevant which I see once the page redirects:

![screenshot from 2017-08-16 23-56-53](https://user-images.githubusercontent.com/223655/29387047-a4199b2a-82de-11e7-9bf0-46bb0e05c448.png)

> Also, do you have second password active?

Not as far as I know. I did have an alias which doesn't seem to work anymore (I haven't logged in for several months)

**Comment by jtormey** [comment] 2017-08-16 22:08
Good to know, do you remember upgrading from a v2 wallet to a v3 wallet ever? (This change took place well over a year ago)

**Comment by spacecowboy** [comment] 2017-08-16 22:10
I have vague memory of an upgrade, not sure what versions were involved. I can see in my mail archive that I last logged in at  2016-12-11

**Comment by spacecowboy** [comment] 2017-08-16 22:13
In case it helps, here is a more complete log (just found the browser settings to make it persistent):

```
Server Time offset 387.875ms - This offset 748  landing-65283d8e886c784d7ca6fa3db308f4d0c91adfa4.min.js:368:1218
Stop!  landing-65283d8e886c784d7ca6fa3db308f4d0c91adfa4.min.js:368:1218
This browser feature is intended for developers. If someone told you to copy-paste something here, it is a scam and will give them access to your money!  landing-65283d8e886c784d7ca6fa3db308f4d0c91adfa4.min.js:368:1218
{"btcBalance":102341425,"ethBalance":0}  landing-65283d8e886c784d7ca6fa3db308f4d0c91adfa4.min.js:368:1218
Panic The wallet was not fully enc/decrypted  landing-65283d8e886c784d7ca6fa3db308f4d0c91adfa4.min.js:368:1218
Error: Save disabled.  my-wallet-846a498f0b9dcb13ae13e14419acef726d69243a.min.js:1:146129
	panic https://blockchain.info/wallet/js/my-wallet-846a498f0b9dcb13ae13e14419acef726d69243a.min.js:1:146129
	syncWallet https://blockchain.info/wallet/js/my-wallet-846a498f0b9dcb13ae13e14419acef726d69243a.min.js:1:146209
	trigger/timer< https://blockchain.info/wallet/js/my-wallet-846a498f0b9dcb13ae13e14419acef726d69243a.min.js:1:45716
Failed to fetch metadata entry 2 at 1MhyZWgBvoJvJaHy4cMNRvZyVbtpnmsmym: DOMException [AbortError: "The operation was aborted. "
code: 20
nsresult: 0x80530014]  my-wallet-846a498f0b9dcb13ae13e14419acef726d69243a.min.js:1:260642
	Blockchain</</Metadata.prototype.fetch/</< https://blockchain.info/wallet/js/my-wallet-846a498f0b9dcb13ae13e14419acef726d69243a.min.js:1:260642
TypeError: NetworkError when attempting to fetch resource.  (unknown)
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://blockchain.info https://www.google-analytics.com”). Source: onfocusin attribute on DIV element.  blockchain.info
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.  blockchain.info:1
Connect wss://ws.blockchain.info/inv  shared.min.js:1:1446
```

The mentioning of `Panic The wallet was not fully enc/decrypted` seems concerning

**Comment by jtormey** [comment] 2017-08-16 22:35
Thanks for the extra info! It looks like you have a very old wallet file, and at some point it must have been corrupted, which is the cause of the issue you're seeing now. I've asked our support staff to put us in contact directly, from there I can look into what exactly was corrupted and help you recover your wallet. Closing this for now.

**Closed by jtormey** 2017-08-16 22:35 UTC
